# GENERATED FILE -- do not hand-edit.
# Rendered from jail.conf.d/mariadb.conf.tmpl + env.conf by
# freebsd/generate-jail-conf.sh. Re-running that script overwrites
# any changes made directly to this file.
#
mariadb {
    host.hostname = "mariadb.amc202d.lan";
    path = "/jails/mariadb";

    vnet;
    vnet.interface = "epair7b";

    exec.prestart  = "ifconfig epair7 create";
    exec.prestart += "ifconfig vm-public addm epair7a";
    exec.prestart += "ifconfig epair7a up";
    exec.start    += "ifconfig epair7b 10.8.0.100/11 up";
    exec.start    += "ifconfig epair7b inet6 2001:8a0:6a32:2100::100/64 up";
    exec.start    += "route add default 10.0.0.254";
    exec.start    += "route add -6 default fe80::9e05:d6ff:fe65:5a7f%epair7b";
    exec.start    += "/bin/sh /etc/rc";
    exec.poststop  = "ifconfig epair7a destroy";
}
